name: Test deploy on AWS runner
on: 
   push: 
       branches: ['master']
jobs:
   start-deploy:
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cleanup services and binaries
      run: |
          sudo docker rm -f chronos
    - name: Start services
      run: |
          cd _work/chronos/chronos
          sudo docker-compose up -d --build
          
